services:
  db:
    image: postgres:16.2 # Version 16.2 of Postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432 # Expose the database on the specified port from the container to the host
    volumes:
      - ./db-data:/var/lib/postgresql/data # Persist the database data in the host machine
  inmemory:
    image: redis:6.2.6 # Version 6.2.6 of Redis
    ports:
      - ${REDIS_PORT}:6379 # Expose the Redis server on the specified port from the container to the host
    volumes:
      - ./redis-data:/data # Persist the Redis data in the host machine
  server:
    # Caddy server
    image: caddy:2.4.6 # Version 2.4.6 of Caddy
    ports:
      - ${SERVER_PORT}:80 # Expose the server on the specified port from the container to the host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Mount the Caddyfile in the container
      - ./public:/srv # Mount the public directory in the container

    



