services:
  db:
    image: postgres:16.2 # Version 16.2 of Postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432 # Expose the database on the specified port from the container to the host
    volumes:
      - ./db-data:/var/lib/postgresql/data # Persist the database data in the host machine

    